---
  kind: Service
  apiVersion: v1
  metadata:
    name: pipelinepoc
  spec:
    clusterIP: None
    selector:
      app: pipelinepoc
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: ui

